# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

import grpc_pb2 as grpcService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION}, '
        f'but the generated code is at version {GRPC_GENERATED_VERSION}.'
    )


class grpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/grpcService/Add',
                request_serializer=grpcService__pb2.addMsg.SerializeToString,
                response_deserializer=grpcService__pb2.addReply.FromString,
                _registered_method=True)
        self.DotProduct = channel.unary_unary(
                '/grpcService/DotProduct',
                request_serializer=grpcService__pb2.dotProductMsg.SerializeToString,
                response_deserializer=grpcService__pb2.dotProductReply.FromString,
                _registered_method=True)
        self.RawImage = channel.unary_unary(
                '/grpcService/RawImage',
                request_serializer=grpcService__pb2.rawImageMsg.SerializeToString,
                response_deserializer=grpcService__pb2.imageReply.FromString,
                _registered_method=True)
        self.JsonImage = channel.unary_unary(
                '/grpcService/JsonImage',
                request_serializer=grpcService__pb2.jsonImageMsg.SerializeToString,
                response_deserializer=grpcService__pb2.imageReply.FromString,
                _registered_method=True)


class grpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DotProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RawImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JsonImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_grpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=grpcService__pb2.addMsg.FromString,
                    response_serializer=grpcService__pb2.addReply.SerializeToString,
            ),
            'DotProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DotProduct,
                    request_deserializer=grpcService__pb2.dotProductMsg.FromString,
                    response_serializer=grpcService__pb2.dotProductReply.SerializeToString,
            ),
            'RawImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RawImage,
                    request_deserializer=grpcService__pb2.rawImageMsg.FromString,
                    response_serializer=grpcService__pb2.imageReply.SerializeToString,
            ),
            'JsonImage': grpc.unary_unary_rpc_method_handler(
                    servicer.JsonImage,
                    request_deserializer=grpcService__pb2.jsonImageMsg.FromString,
                    response_serializer=grpcService__pb2.imageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
